services:
  postgresql:
    container_name: postgresql
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - ./postgresql/sql:/docker-entrypoint-initdb.d
    restart: always
  tailwindcss:
    container_name: tailwindcss
    image: node:22-alpine
    tty: true
    working_dir: /app
    volumes:
      - ../:/app
    command: sh -c "npx tailwindcss -i ./src/main/resources/static/css/input.css -o ./src/main/resources/static/css/tailwind.css --watch"

networks:
  tabisketch:
