name: jar_build

on:
  pull_request:

jobs:
  jar_build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      matrix:
        runner: [ubuntu-latest]
        node: [20]
    name: build on node ${{ matrix.node }} ${{ matrix.runner }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: tabisketch
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: init db
        run: ./bin/init_db.sh
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: tabisketch
      - name: build jar
        run: ./mvnw package
        env:
          DATABASE_URL: jdbc:postgresql://localhost:5432/tabisketch
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          MAIL_USERNAME: test
          MAIL_PASSWORD: test
